### ISSUE TITLE
Query about documentation

### ISSUE THREAD

**Issue by amarux** [eubr-bigsea/py-st-dbscan#10]
Nice project and really useful for many applications. 
The comments on stdbscan.py at line 20 indicated  
`:param temporal_threshold: Maximum non-spatial distance value (meters);`

I think the units could be wrong for a temporal threshold. Would be minutes instead of meters?

**Comment by lucasmsp** [comment]
Thank you. 

Indeed the docstring was misspelled. The `temporal_threshold` is given in seconds, while the `spartial_thresold` in meters. I already fix it in master, Thank you.
