### ISSUE TITLE
Vertical Spatial Shapes

### ISSUE THREAD

**Issue by DavidRimar** [eubr-bigsea/py-st-dbscan#11]
Hi,

I am probably making a mistake somewhere but the resulting spatial clusters seemingly fit into vertical lines which just don't make any sense (see image from QGIS showing 3 of the largest clusters). 

![image](https://user-images.githubusercontent.com/38216799/122115532-e3261380-ce24-11eb-8ed2-44c5736e6e3d.png)

I have not modified any of your scripts, I have basically just supplied another dataset. The parameters I have used are:

spatial_threshold = 5000  # meters
temporal_threshold = 4320  # seconds
min_neighbors = 5

When it comes to GIS conversion, my lon lat coordinates are in epsg 4326 and I have used the convert_to_utm() method from src_epsg=4326 to dst_epsg=27700 (I have also tried other dst types).

Do you have any ideas why such cluster could occur? Any knowledge of this being an issue? Or thoughts what I am doing wrong?

Any comments much appreciated!

David

**Comment by lucasmsp** [comment]
Hi, the stdbscan (and dbscan as well) is very sensitive to the parameters. The parameters spatial_threshold and temporal_threshold depend heavily on your knowledge of the data input. 

For instance, we can see on your map that points inside the yellow cluster have a spatial distance from the red cluster. Also, the blue cluster may have a temporal distance from the red cluster. By just looking into your map, I think you should decrease the spatial_threshold, 5 km seems very high to me. 

Let me know if it works, 
Lucas

**Comment by DavidRimar** [comment]
Hi Luca, apologies, I had made a data preprocessing error prior to using the algorithm so I close this issue, your script works great!
