### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by ibayer** [eubr-bigsea/py-st-dbscan#3]
Hi, 

your implementation looks interesting and I would like to test it on a project of mine. Would it be possible to release the code under a OSS license?
https://help.github.com/articles/licensing-a-repository/

Best,
ibayer

**Comment by lucasmsp** [comment]
Hi ibayer,

We added an Apache License.

Thanks,
Lucas Ponce

**Comment by ibayer** [comment]
Thanks, much appreciated!
