### ISSUE TITLE
SettingWithCopyWarning

### ISSUE THREAD

**Issue by ibayer** [eubr-bigsea/py-st-dbscan#6]
I didn't check if its influences the results but it does sound a bit dangerous.

``` bash
$ /st_dbscan/python/src/stdbscan.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df['cluster'] = unmarked
```

**Comment by lucasmsp** [comment]
Hi, which pandas's version do you use? I could not reproduce your issue.

Thank you,

**Comment by ibayer** [comment]
I don't have access to the project anymore. Thanks for the feedback I think we can close this if it's not reproducible for a recent version of pandas.
