### ISSUE TITLE
algorithm takes around 1 min for 3000 points

### ISSUE THREAD

**Issue by kalyanlimkar-3** [eubr-bigsea/py-st-dbscan#8]

**Comment by kalyanlimkar-3** [comment]
I ran this algo and it was taking around 1 min for 3000 points. is this normal?
Edit: I read the data incorrectly, it is 3000 points not 10000

**Comment by lucasmsp** [comment]
Hi ! The algorithm being a variation of dbscan is subject to a similar order of complexity. In addition, the cost of the distance (great-circle) function is heavier. In general, you could use the same dbscan optimizations: change the input parameters or use a R-tree structure to minimize the search for neighbors. Also, a quick change is to work through time as integer type to speedup on execution.

Anyway, I added a update that gives a speedup ~ 1.5x from better pandas usage.

**Comment by kalyanlimkar-3** [comment]
Now the algo takes around 30 secs which is better. I will implement r-tree structure for retrieving neighbors. Thanks for a quick reply.

**Comment by kalyanlimkar-3** [comment]
Hey, can you help me in implementing r-tree structure?
